[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
berrie_staking = "GPyfu6b3jbLHUpHx58HjBx2pZuGsYydKjC66UqqTtGua"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/athdoSSvTJoAxt9DY7cFrbGynu7Bv1MQUUB8NSstAD3.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[package]
name = "berrie_staking"
version = "0.1.0"
