[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[package]
name = "berrie-staking"
version = "0.1.0"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
berrie_staking = "4uSH1hFYxMf4CjzuKwh65hsawAso4ej3bRKGVYJ4gLSn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/athdoSSvTJoAxt9DY7cFrbGynu7Bv1MQUUB8NSstAD3.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
